# Generates the backend registry's PCI dispatch table from the family
# manifests.
#
# src\common\backend_registry.c used to restate every claimed PCI id as a
# hand-written if-chain, which is exactly the duplication the family matrix
# was built to catch elsewhere - and the file every new family had to edit to
# exist. The manifests are the single statement of which chip belongs to which
# family; this emitter turns that statement into the checked-in
# src\common\backend_registry_table.inc, and check-tree.ps1 regenerates and
# compares so an edited manifest cannot silently diverge from the compiled
# dispatch.
#
# The table preserves the registry's allowlist meaning unchanged: a row exists
# only because a manifest lists the id. It no longer follows that someone has
# run every row - a chip's aliases are ids the chip's own code drives unchanged
# but which have run nowhere, and they are emitted here because an id the INF
# binds and this table does not know would install and then resolve no backend.
# Each alias row says so in its comment. Get-V9xFamilies has already asserted
# that no PCI id is claimed twice, so row order cannot change what a lookup
# returns; families are emitted in Get-V9xFamilyIds order (sorted), chips in
# manifest order and each chip's aliases directly after it, which keeps the
# file byte-stable for the comparison.

function Get-V9xBackendRegistryTableLines {
    param([Parameter(Mandatory = $true)][string]$RepoRoot)

    . (Join-Path $PSScriptRoot "family.ps1")
    $families = @(Get-V9xFamilies -RepoRoot $RepoRoot)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("/*")
    $lines.Add(" * Generated by scripts\lib\backend-registry.ps1 from")
    $lines.Add(" * packaging\families\*\family.psd1. Do not edit: run")
    $lines.Add(" * scripts\update-backend-registry.ps1. check-tree.ps1 fails when this")
    $lines.Add(" * file disagrees with the manifests.")
    $lines.Add(" *")
    $lines.Add(" * Included only by src\common\backend_registry.c, which defines the row")
    $lines.Add(" * struct and owns the allowlist policy this table carries.")
    $lines.Add(" */")
    foreach ($header in @($families | ForEach-Object { $_.Backend.Header } |
                          Sort-Object -Unique)) {
        $lines.Add('#include "' + $header + '"')
    }
    $lines.Add("")
    $lines.Add("static const struct v9x_backend_registry_row v9x_backend_registry_rows[] = {")
    foreach ($family in $families) {
        foreach ($entry in @(Get-V9xFamilyPciEntries -Family $family)) {
            $note = $family.Id + " / " + $entry.ChipId
            if ($entry.IsAlias) {
                $note += " alias"
            }
            $lines.Add("    { 0x" + $entry.VendorId + "u, 0x" + $entry.DeviceId +
                       "u, " + $family.Backend.Getter + " }, /* " + $note + " */")
        }
    }
    $lines.Add("};")
    $lines
}

function Write-V9xBackendRegistryTable {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [Parameter(Mandatory = $true)][string]$OutputPath
    )

    $lines = Get-V9xBackendRegistryTableLines -RepoRoot $RepoRoot
    Set-Content -LiteralPath $OutputPath -Encoding Ascii -Value $lines
    $OutputPath
}
