# Generates the family matrix the host tests assert against.
#
# The manifests are the single statement of which chip belongs to which family,
# what its engine claims, and which modes its INF advertises. Everything else -
# the backend registry's PCI dispatch, the engine capability masks, the mode
# tables - restates some of that in C, by hand. Generating the manifest side and
# asserting the C side against it is what turns that duplication from a thing
# that can silently disagree into a thing that fails the build.
#
# Dot-sourced by both host build scripts so the Watcom and MSVC passes compile
# the same generated header.

function Write-V9xFamilyMatrixHeader {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [Parameter(Mandatory = $true)][string]$OutputDir
    )

    . (Join-Path $PSScriptRoot "family.ps1")
    $families = @(Get-V9xFamilies -RepoRoot $RepoRoot)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("/*")
    $lines.Add(" * Generated by scripts\lib\family-matrix.ps1 from")
    $lines.Add(" * packaging\families\*\family.psd1. Do not edit: rerun the host build.")
    $lines.Add(" */")
    $lines.Add("#ifndef VELOCITY9X_FAMILY_MATRIX_H")
    $lines.Add("#define VELOCITY9X_FAMILY_MATRIX_H")
    $lines.Add("")
    $lines.Add('#include "velocity9x/engine_abi.h"')
    $lines.Add("")
    $lines.Add("struct v9x_family_matrix_mode {")
    $lines.Add("    unsigned short width;")
    $lines.Add("    unsigned short height;")
    $lines.Add("    unsigned short bits_per_pixel;")
    $lines.Add("    unsigned short vbe_mode;")
    $lines.Add("};")
    $lines.Add("")
    $lines.Add("struct v9x_family_matrix_chip {")
    $lines.Add("    const char *family_id;")
    $lines.Add("    const char *chip_id;")
    $lines.Add("    unsigned short vendor_id;")
    $lines.Add("    unsigned short device_id;")
    $lines.Add("    unsigned long engine_type;")
    $lines.Add("    unsigned long engine_caps;")
    $lines.Add("    unsigned long video_memory_bytes;")
    $lines.Add("    const struct v9x_family_matrix_mode *modes;")
    $lines.Add("    unsigned short mode_count;")
    $lines.Add("};")
    $lines.Add("")
    $lines.Add("/*")
    $lines.Add(" * A chip's aliases: further PCI device ids the chip's own code drives")
    $lines.Add(" * unchanged. chip_index is the row above that owns the alias, which is what")
    $lines.Add(" * lets a test assert the two resolve to the same backend rather than only")
    $lines.Add(" * that the alias resolves to something.")
    $lines.Add(" */")
    $lines.Add("struct v9x_family_matrix_alias {")
    $lines.Add("    const char *family_id;")
    $lines.Add("    const char *chip_id;")
    $lines.Add("    unsigned short vendor_id;")
    $lines.Add("    unsigned short device_id;")
    $lines.Add("    unsigned short chip_index;")
    $lines.Add("};")
    $lines.Add("")

    $chipIndex = 0
    $aliasCount = 0
    $rows = [System.Collections.Generic.List[string]]::new()
    $aliasRows = [System.Collections.Generic.List[string]]::new()
    foreach ($family in $families) {
        foreach ($chip in @($family.Chips)) {
            $modeSymbol = "v9x_family_matrix_modes_$chipIndex"
            $lines.Add("static const struct v9x_family_matrix_mode ${modeSymbol}[] = {")
            foreach ($mode in @($chip.Modes)) {
                # VbeMode is a four-digit hex string in the manifest ('0111'),
                # which is how the INF and the C tables both spell it.
                $lines.Add("    { " + [int]$mode.Width + "u, " + [int]$mode.Height +
                           "u, " + [int]$mode.BitsPerPixel + "u, 0x" +
                           $mode.VbeMode + "u },")
            }
            $lines.Add("};")
            $lines.Add("")

            $caps = @($chip.EngineCaps | ForEach-Object { "V9X_DD_ENGINE_CAP_$_" })
            $capsExpression = if ($caps.Count -eq 0) {
                "0ul"
            } else {
                $caps -join " |`n          "
            }
            # One Add per line rather than one formatted block: -f binds tighter
            # than +, so a concatenated format string would silently take its
            # arguments for the last fragment alone.
            $rows.Add('    { "' + $family.Id + '", "' + $chip.Id + '",')
            $rows.Add('      0x' + $chip.VendorId + 'u, 0x' + $chip.DeviceId + 'u,')
            $rows.Add('      V9X_DD_ENGINE_TYPE_' + $chip.EngineType + ',')
            $rows.Add('      ' + $capsExpression + ',')
            $rows.Add('      ' + ([uint32]$chip.VideoMemoryBytes) + 'ul,')
            $rows.Add('      ' + $modeSymbol + ',')
            $rows.Add('      (unsigned short)(sizeof(' + $modeSymbol + ') / sizeof(' +
                      $modeSymbol + '[0])) },')

            foreach ($alias in @($chip.Aliases | Where-Object { $_ })) {
                $aliasRows.Add('    { "' + $family.Id + '", "' + $chip.Id + '", 0x' +
                               $chip.VendorId + 'u, 0x' + $alias.DeviceId + 'u, ' +
                               $chipIndex + 'u },')
                ++$aliasCount
            }
            ++$chipIndex
        }
    }
    $lines.Add("static const struct v9x_family_matrix_chip v9x_family_matrix[] = {")
    $lines.AddRange([string[]]$rows)
    $lines.Add("};")
    $lines.Add("")
    $lines.Add("#define V9X_FAMILY_MATRIX_COUNT ${chipIndex}u")
    $lines.Add("")
    # An empty C array is not valid C89, so a tree with no aliases at all still
    # emits one unreachable row rather than nothing; the count is what the
    # tests loop over.
    $lines.Add("static const struct v9x_family_matrix_alias v9x_family_matrix_aliases[] = {")
    if ($aliasCount -eq 0) {
        $lines.Add('    { "", "", 0u, 0u, 0u }')
    } else {
        $lines.AddRange([string[]]$aliasRows)
    }
    $lines.Add("};")
    $lines.Add("")
    $lines.Add("#define V9X_FAMILY_MATRIX_ALIAS_COUNT ${aliasCount}u")
    $lines.Add("")
    $lines.Add("#endif")

    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    $path = Join-Path $OutputDir "v9x_family_matrix.h"
    Set-Content -LiteralPath $path -Encoding Ascii -Value $lines
    Write-Verbose "Generated $path for $chipIndex chip(s)."
    $path
}
