# Generates the OpenGL 1.1 dispatch table from the manifest.
#
# src\opengl\gl_entrypoints.psd1 is the one statement of the 336 slots of
# GLCLTPROCTABLE.glDispatchTable: slot, name, return type, parameter list,
# cross-checked against ReactOS icd.h and Mesa gldrv.h on 2026-09-26. The ICD
# needs a typed function pointer, a typed stub and a table entry per slot, and
# the host test needs the names in order; generating all of it from the one
# file is what keeps a hand-typed copy from drifting (the same reason
# scripts\lib\family-matrix.ps1 exists). Dot-sourced by the host build scripts
# and by scripts\build-opengl-icd.ps1.
#
# The includer defines, before including the generated header:
#   V9X_GL_API           the calling convention of a slot (__stdcall)
#   V9X_GL_STUB_HOOK(n)  what a stub does before returning zero; the ICD counts
#                        the slot, the host test records it
# and gets:
#   V9X_GL_SLOT_COUNT, V9X_GL_SLOT_NAMES (an initialiser of 336 strings),
#   V9X_GL_PFN_<name> typedefs, v9x_gl_stub_<name> static definitions when
#   V9X_GL_DEFINE_STUBS is defined, and V9X_GL_DISPATCH_INIT (an initialiser
#   of 336 V9X_GL_PROC values in slot order).

function Write-V9xGlDispatchHeader {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [Parameter(Mandatory = $true)][string]$OutputDir
    )

    $manifestPath = Join-Path $RepoRoot "src\opengl\gl_entrypoints.psd1"
    $manifest = Import-PowerShellDataFile -LiteralPath $manifestPath
    $entries = @($manifest.Entries)
    if ($entries.Count -ne 336) {
        throw "gl_entrypoints.psd1 has $($entries.Count) entries; the 1.1 table has 336."
    }
    for ($i = 0; $i -lt $entries.Count; $i++) {
        if ([int]$entries[$i].Slot -ne $i) {
            throw "gl_entrypoints.psd1 entry $i has Slot $($entries[$i].Slot)."
        }
    }
    $names = @($entries | ForEach-Object { $_.Name })
    if (($names | Sort-Object -Unique).Count -ne $names.Count) {
        throw "gl_entrypoints.psd1 has a duplicate name."
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("/*")
    $lines.Add(" * Generated by scripts\lib\gl-dispatch.ps1 from")
    $lines.Add(" * src\opengl\gl_entrypoints.psd1. Do not edit: rerun the build.")
    $lines.Add(" */")
    $lines.Add("#ifndef VELOCITY9X_GL_DISPATCH_GEN_H")
    $lines.Add("#define VELOCITY9X_GL_DISPATCH_GEN_H")
    $lines.Add("")
    $lines.Add('#include "velocity9x/gl_types.h"')
    $lines.Add("")
    $lines.Add("#ifndef V9X_GL_API")
    $lines.Add("#error V9X_GL_API must name the slot calling convention before this header")
    $lines.Add("#endif")
    $lines.Add("")
    $lines.Add("#define V9X_GL_SLOT_COUNT $($entries.Count)")
    $lines.Add("typedef void (V9X_GL_API *V9X_GL_PROC)(void);")
    $lines.Add("")
    $lines.Add("#define V9X_GL_SLOT_NAMES { \")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $sep = if ($i -lt $entries.Count - 1) { "," } else { "" }
        $lines.Add("    `"$($entries[$i].Name)`"$sep \")
    }
    $lines.Add("}")
    $lines.Add("")
    foreach ($e in $entries) {
        $lines.Add("typedef $($e.Return) (V9X_GL_API *V9X_GL_PFN_$($e.Name))($($e.Params));")
    }
    $lines.Add("")
    $lines.Add("#ifdef V9X_GL_DEFINE_STUBS")
    foreach ($e in $entries) {
        $ret = [string]$e.Return
        $params = [string]$e.Params
        $body = @()
        if ($params -ne 'void') {
            foreach ($p in ($params -split ',')) {
                $token = ($p.Trim() -replace '\[.*\]$', '')
                $name = ($token -split '\s+')[-1].TrimStart('*')
                if ($name -eq '') { throw "Cannot name a parameter of $($e.Name): '$p'" }
                $body += "(void)$name;"
            }
        }
        $body += "V9X_GL_STUB_HOOK($($e.Slot));"
        if ($ret -ne 'void') {
            $body += "return ($ret)0;"
        }
        $lines.Add("static $ret V9X_GL_API v9x_gl_stub_$($e.Name)($params) { $($body -join ' ') }")
    }
    $lines.Add("#endif /* V9X_GL_DEFINE_STUBS */")
    $lines.Add("")
    $lines.Add("#define V9X_GL_DISPATCH_INIT { \")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $sep = if ($i -lt $entries.Count - 1) { "," } else { "" }
        $lines.Add("    (V9X_GL_PROC)v9x_gl_stub_$($entries[$i].Name)$sep \")
    }
    $lines.Add("}")
    $lines.Add("")
    $lines.Add("#endif /* VELOCITY9X_GL_DISPATCH_GEN_H */")

    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    $target = Join-Path $OutputDir "gl_dispatch_gen.h"
    [System.IO.File]::WriteAllLines($target, $lines, (New-Object System.Text.UTF8Encoding($false)))
    return $target
}
