# Generates the Glide 3.x export scaffolding from the manifest.
#
# src\glide3\glide3_entrypoints.psd1 is the one statement of the 99 exports
# GLIDE3X.DLL carries: name, argument bytes and return kind. From it come
# the export indices, the names in order, the stub definitions and the
# decorated names the linker exports, as scripts\lib\glide-exports.ps1 does
# for Glide 2. Dot-sourced by scripts\build-glide3.ps1.
#
# The front end (src\glide3\glide3_dll.c) writes the exports Diablo II and
# Rollcage import, and a few state calls beside them, by hand; their names
# are listed in $script:V9xGlide3Written and every other export gets a
# generated stub
# that hands its arguments to V9X_GLIDE3_STUB_HOOK(ix, args, count) and
# returns zero. A hand-written export whose parameters disagree with the
# manifest leaves its decorated name unresolved, so the link checks them.

$script:V9xGlide3ExportCount = 99
$script:V9xGlide3DiabloCount = 36
$script:V9xGlide3RollcageCount = 42
$script:V9xGlide3Written = @(
    'grGet', 'grGetString', 'grQueryResolutions',
    'grGlideInit', 'grGlideShutdown', 'grSstSelect', 'grSstWinOpen',
    'grSstWinClose', 'grSelectContext', 'grFinish', 'grFlush',
    'grBufferClear', 'grBufferSwap', 'grRenderBuffer', 'grClipWindow',
    'grColorMask', 'grCoordinateSpace',
    'grCullMode', 'grDepthBufferMode', 'grDepthBufferFunction', 'grDepthMask',
    'grDepthBiasLevel', 'grDitherMode', 'grAlphaTestFunction',
    'grAlphaTestReferenceValue', 'grChromakeyMode', 'grChromakeyValue',
    'grFogColorValue', 'grConstantColorValue', 'grFogMode', 'grFogTable',
    'grAlphaBlendFunction', 'grColorCombine', 'grAlphaCombine',
    'grLoadGammaTable', 'guGammaCorrectionRGB',
    'grTexClampMode', 'grTexFilterMode', 'grTexMipMapMode', 'grTexCombine',
    'grTexMinAddress', 'grTexMaxAddress', 'grTexTextureMemRequired',
    'grTexCalcMemRequired', 'grTexSource', 'grTexDownloadMipMap',
    'grTexDownloadTable',
    'grVertexLayout', 'grDrawVertexArray', 'grDrawVertexArrayContiguous',
    'grDrawTriangle', 'grDrawLine', 'grDrawPoint',
    'grLfbLock', 'grLfbUnlock'
)

function Get-V9xGlide3Entries {
    param([Parameter(Mandatory = $true)][string]$RepoRoot)

    $manifestPath = Join-Path $RepoRoot "src\glide3\glide3_entrypoints.psd1"
    $manifest = Import-PowerShellDataFile -LiteralPath $manifestPath
    $entries = @($manifest.Entries)
    if ($entries.Count -ne $script:V9xGlide3ExportCount) {
        throw "glide3_entrypoints.psd1 has $($entries.Count) entries; 3dfx's GLIDE3X.DLL exports $script:V9xGlide3ExportCount."
    }
    $names = @($entries | ForEach-Object { $_.Name })
    if (($names | Sort-Object -Unique).Count -ne $names.Count) {
        throw "glide3_entrypoints.psd1 has a duplicate name."
    }
    foreach ($e in $entries) {
        if ([string]$e.Name -notmatch '^[A-Za-z][A-Za-z0-9]*$') {
            throw "glide3_entrypoints.psd1: bad name '$($e.Name)'."
        }
        if (([int]$e.Bytes % 4) -ne 0 -or [int]$e.Bytes -lt 0 -or [int]$e.Bytes -gt 64) {
            throw "glide3_entrypoints.psd1: $($e.Name) has Bytes $($e.Bytes)."
        }
        if ([string]$e.Return -notin @('void', 'u32', 'float')) {
            throw "glide3_entrypoints.psd1: $($e.Name) has Return '$($e.Return)'."
        }
        if ([string]$e.Use -notin @('Diablo', 'Rollcage', 'Both', 'Other')) {
            throw "glide3_entrypoints.psd1: $($e.Name) has Use '$($e.Use)'."
        }
    }
    $diablo = @($entries | Where-Object { $_.Use -in @('Diablo', 'Both') }).Count
    if ($diablo -ne $script:V9xGlide3DiabloCount) {
        throw "glide3_entrypoints.psd1 marks $diablo Diablo entries; D2Glide.dll imports $script:V9xGlide3DiabloCount."
    }
    $rollcage = @($entries | Where-Object { $_.Use -in @('Rollcage', 'Both') }).Count
    if ($rollcage -ne $script:V9xGlide3RollcageCount) {
        throw "glide3_entrypoints.psd1 marks $rollcage Rollcage entries; its ROLLCAGE.EXE imports $script:V9xGlide3RollcageCount."
    }
    foreach ($name in $script:V9xGlide3Written) {
        if ($name -notin $names) {
            throw "glide3-exports.ps1 lists '$name' as written, but the manifest has no such export."
        }
    }
    return $entries
}

# The decorated name the linker exports and a game imports: _name@bytes.
function Get-V9xGlide3ExportSymbol {
    param([Parameter(Mandatory = $true)]$Entry)
    return "_$($Entry.Name)@$([int]$Entry.Bytes)"
}

function Write-V9xGlide3ExportHeader {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [Parameter(Mandatory = $true)][string]$OutputDir
    )

    $entries = Get-V9xGlide3Entries -RepoRoot $RepoRoot
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("/*")
    $lines.Add(" * Generated by scripts\lib\glide3-exports.ps1 from")
    $lines.Add(" * src\glide3\glide3_entrypoints.psd1. Do not edit: rerun the build.")
    $lines.Add(" */")
    $lines.Add("#ifndef VELOCITY9X_GLIDE3_EXPORTS_GEN_H")
    $lines.Add("#define VELOCITY9X_GLIDE3_EXPORTS_GEN_H")
    $lines.Add("")
    $lines.Add('#include "velocity9x/types.h"')
    $lines.Add("")
    $lines.Add("#define V9X_GLIDE3_EXPORT_COUNT $($entries.Count)")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $lines.Add("#define V9X_GLIDE3_IX_$($entries[$i].Name) $i")
    }
    $lines.Add("")
    $lines.Add("#define V9X_GLIDE3_EXPORT_NAMES { \")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $sep = if ($i -lt $entries.Count - 1) { "," } else { "" }
        $lines.Add("    `"$($entries[$i].Name)`"$sep \")
    }
    $lines.Add("}")
    $lines.Add("")
    $lines.Add("#ifdef V9X_GLIDE3_DEFINE_STUBS")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $e = $entries[$i]
        if ($e.Name -in $script:V9xGlide3Written) { continue }
        $count = [int]$e.Bytes / 4
        $params = if ($count -eq 0) { 'void' } else {
            (@(0..($count - 1) | ForEach-Object { "v9x_u32 a$_" }) -join ', ')
        }
        $ret = switch ([string]$e.Return) { 'void' { 'void' } 'u32' { 'v9x_u32' } 'float' { 'float' } }
        $body = @()
        if ($count -gt 0) {
            # Copied into an array rather than addressed on the stack, so
            # the hook never depends on where the compiler keeps a0..aN.
            $body += "v9x_u32 v[$count];"
            $body += @(0..($count - 1) | ForEach-Object { "v[$_] = a$_;" })
            $body += "V9X_GLIDE3_STUB_HOOK($i, v, $count);"
        } else {
            $body += "V9X_GLIDE3_STUB_HOOK($i, 0, 0);"
        }
        if ($ret -eq 'v9x_u32') { $body += "return 0ul;" }
        if ($ret -eq 'float') { $body += "return 0.0f;" }
        $lines.Add("$ret __stdcall $($e.Name)($params);")
        $lines.Add("$ret __stdcall $($e.Name)($params) { $($body -join ' ') }")
    }
    $lines.Add("#endif /* V9X_GLIDE3_DEFINE_STUBS */")
    $lines.Add("")
    $lines.Add("#endif /* VELOCITY9X_GLIDE3_EXPORTS_GEN_H */")

    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    $target = Join-Path $OutputDir "glide3_exports_gen.h"
    [System.IO.File]::WriteAllLines($target, $lines, (New-Object System.Text.UTF8Encoding($false)))
    return $target
}
