# Generates the Glide 2.x export scaffolding from the manifest.
#
# src\glide\glide_entrypoints.psd1 is the one statement of the 130 exports
# GLIDE2X.DLL carries: name, argument bytes, return kind, and whether
# glide_dll.c defines it by hand or the generated stub stands in. The DLL
# needs an index per export (its call counters), the names in that order,
# and the stubs; the build script needs the decorated export names. Deriving
# all of them from the one file is what keeps them from drifting (the same
# reason scripts\lib\gl-dispatch.ps1 exists). Dot-sourced by
# scripts\build-glide.ps1; check-tree.ps1 reads the manifest directly.
#
# The includer defines, before including the generated header:
#   V9X_GLIDE_STUB_HOOK(ix)  what a stub does before returning zero
# and gets:
#   V9X_GLIDE_EXPORT_COUNT, V9X_GLIDE_IX_<name> per export,
#   V9X_GLIDE_EXPORT_NAMES (an initialiser of the names in manifest order),
#   and, when V9X_GLIDE_DEFINE_STUBS is defined, the stub definitions.
#
# A Written export is checked by the link instead: Watcom decorates a
# __stdcall definition with its argument bytes, so a hand-written function
# whose parameters disagree with the manifest leaves the export unresolved.

$script:V9xGlideExportCount = 130
# NFS II SE's 50 imports, plus grHints, grConstantColorValue,
# grConstantColorValue4, guColorCombineFunction and grTexTextureMemRequired
# for Carmageddon II (2026-10-11).
$script:V9xGlideWrittenCount = 55

function Get-V9xGlideEntries {
    param([Parameter(Mandatory = $true)][string]$RepoRoot)

    $manifestPath = Join-Path $RepoRoot "src\glide\glide_entrypoints.psd1"
    $manifest = Import-PowerShellDataFile -LiteralPath $manifestPath
    $entries = @($manifest.Entries)
    if ($entries.Count -ne $script:V9xGlideExportCount) {
        throw "glide_entrypoints.psd1 has $($entries.Count) entries; retail GLIDE2X.DLL exports $script:V9xGlideExportCount."
    }
    $names = @($entries | ForEach-Object { $_.Name })
    if (($names | Sort-Object -Unique).Count -ne $names.Count) {
        throw "glide_entrypoints.psd1 has a duplicate name."
    }
    foreach ($e in $entries) {
        if ([string]$e.Name -notmatch '^[A-Za-z][A-Za-z0-9]*$') {
            throw "glide_entrypoints.psd1: bad name '$($e.Name)'."
        }
        if (([int]$e.Bytes % 4) -ne 0 -or [int]$e.Bytes -lt 0 -or [int]$e.Bytes -gt 64) {
            throw "glide_entrypoints.psd1: $($e.Name) has Bytes $($e.Bytes)."
        }
        if ([string]$e.Return -notin @('void', 'u32', 'float')) {
            throw "glide_entrypoints.psd1: $($e.Name) has Return '$($e.Return)'."
        }
        if ([string]$e.Kind -notin @('Written', 'Stub')) {
            throw "glide_entrypoints.psd1: $($e.Name) has Kind '$($e.Kind)'."
        }
    }
    $written = @($entries | Where-Object { $_.Kind -eq 'Written' }).Count
    if ($written -ne $script:V9xGlideWrittenCount) {
        throw "glide_entrypoints.psd1 has $written Written entries; expected $script:V9xGlideWrittenCount (NFS2SEA.EXE's imports plus Carmageddon II's five)."
    }
    return $entries
}

# The decorated name the linker exports and a game imports: _name@bytes.
function Get-V9xGlideExportSymbol {
    param([Parameter(Mandatory = $true)]$Entry)
    return "_$($Entry.Name)@$([int]$Entry.Bytes)"
}

function Write-V9xGlideExportHeader {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [Parameter(Mandatory = $true)][string]$OutputDir
    )

    $entries = Get-V9xGlideEntries -RepoRoot $RepoRoot
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("/*")
    $lines.Add(" * Generated by scripts\lib\glide-exports.ps1 from")
    $lines.Add(" * src\glide\glide_entrypoints.psd1. Do not edit: rerun the build.")
    $lines.Add(" */")
    $lines.Add("#ifndef VELOCITY9X_GLIDE_EXPORTS_GEN_H")
    $lines.Add("#define VELOCITY9X_GLIDE_EXPORTS_GEN_H")
    $lines.Add("")
    $lines.Add('#include "velocity9x/types.h"')
    $lines.Add("")
    $lines.Add("#define V9X_GLIDE_EXPORT_COUNT $($entries.Count)")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $lines.Add("#define V9X_GLIDE_IX_$($entries[$i].Name) $i")
    }
    $lines.Add("")
    $lines.Add("#define V9X_GLIDE_EXPORT_NAMES { \")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $sep = if ($i -lt $entries.Count - 1) { "," } else { "" }
        $lines.Add("    `"$($entries[$i].Name)`"$sep \")
    }
    $lines.Add("}")
    $lines.Add("")
    $lines.Add("#ifdef V9X_GLIDE_DEFINE_STUBS")
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $e = $entries[$i]
        if ($e.Kind -ne 'Stub') { continue }
        $count = [int]$e.Bytes / 4
        $params = if ($count -eq 0) { 'void' } else {
            (@(0..($count - 1) | ForEach-Object { "v9x_u32 a$_" }) -join ', ')
        }
        $ret = switch ([string]$e.Return) { 'void' { 'void' } 'u32' { 'v9x_u32' } 'float' { 'float' } }
        $body = @()
        if ($count -gt 0) {
            $body += @(0..($count - 1) | ForEach-Object { "(void)a$_;" })
        }
        $body += "V9X_GLIDE_STUB_HOOK($i);"
        if ($ret -eq 'v9x_u32') { $body += "return 0ul;" }
        if ($ret -eq 'float') { $body += "return 0.0f;" }
        $lines.Add("$ret __stdcall $($e.Name)($params);")
        $lines.Add("$ret __stdcall $($e.Name)($params) { $($body -join ' ') }")
    }
    $lines.Add("#endif /* V9X_GLIDE_DEFINE_STUBS */")
    $lines.Add("")
    $lines.Add("#endif /* VELOCITY9X_GLIDE_EXPORTS_GEN_H */")

    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    $target = Join-Path $OutputDir "glide_exports_gen.h"
    [System.IO.File]::WriteAllLines($target, $lines, (New-Object System.Text.UTF8Encoding($false)))
    return $target
}
